export const API_BASE_URL = "https://arenilac.com/adminpaneli";
export const API_FILE_URL = "https://arenilac.com/adminpaneli/assets/images";
export const API_PDF_URL = "https://arenilac.com/adminpaneli/assets/pdf";

export const API_ENDPOINTS = {
  JSON_ABOUT: `${API_BASE_URL}/jsonList/jsonAbout.php`,
  JSON_ABOUTEN: `${API_BASE_URL}/jsonList/jsonAboutEn.php`,
  JSON_NEWS: `${API_BASE_URL}/jsonList/jsonNews.php`,
  JSON_NEWSEN: `${API_BASE_URL}/jsonList/jsonNewsEn.php`,
  JSON_ASKEDQUESTION: `${API_BASE_URL}/jsonList/jsonAskedQuestion.php`,
  JSON_ASKEDQUESTIONEN: `${API_BASE_URL}/jsonList/jsonAskedQuestionEn.php`,
  JSON_CERTIFICATE: `${API_BASE_URL}/jsonList/jsonCertificate.php`,
  JSON_PKU: `${API_BASE_URL}/jsonList/jsonPku.php`,
  JSON_PKUEN: `${API_BASE_URL}/jsonList/jsonPkuEn.php`,
  JSON_BLOG: `${API_BASE_URL}/jsonList/jsonBlog.php`,
  JSON_BLOGEN: `${API_BASE_URL}/jsonList/jsonBlogEn.php`,
  JSON_FROMYOU: `${API_BASE_URL}/jsonList/jsonFromYou.php`,
  JSON_FROMYOUEN: `${API_BASE_URL}/jsonList/jsonFromYouEn.php`,
  JSON_RECIPESCATEGORY: `${API_BASE_URL}/jsonList/jsonRecipesCategory.php`,
  JSON_RECIPESCATEGORYEN: `${API_BASE_URL}/jsonList/jsonRecipesCategoryEn.php`,
  JSON_RECIPES: `${API_BASE_URL}/jsonList/jsonRecipes.php`,
  JSON_RECIPESEN: `${API_BASE_URL}/jsonList/jsonRecipesEn.php`,
  JSON_PRODUCT: `${API_BASE_URL}/jsonList/jsonProduct.php`,
  JSON_PRODUCTEN: `${API_BASE_URL}/jsonList/jsonProductEn.php`,
  JSON_CONTACT: `${API_BASE_URL}/jsonList/jsonContact.php`,
  JSON_HOME: `${API_BASE_URL}/jsonList/jsonHome.php`,
  JSON_HOMEEN: `${API_BASE_URL}/jsonList/jsonHomeEn.php`,
  JSON_PRODUCT_HOME: `${API_BASE_URL}/jsonList/jsonProductHome.php`,
  JSON_PRODUCT_HOMEEN: `${API_BASE_URL}/jsonList/jsonProductHomeEn.php`,
  JSON_RECIPES_HOME: `${API_BASE_URL}/jsonList/jsonRecipesHome.php`,
  JSON_RECIPES_HOMEEN: `${API_BASE_URL}/jsonList/jsonRecipesHomeEn.php`,
  JSON_PKUCATEGORY: `${API_BASE_URL}/jsonList/jsonPkuCategory.php`,
  JSON_PKUCATEGORYYEN: `${API_BASE_URL}/jsonList/jsonPkuCategoryEn.php`,
  JSON_CONTRACT: `${API_BASE_URL}/jsonList/jsonContract.php`,
  JSON_CONTRACTEN: `${API_BASE_URL}/jsonList/jsonContractEn.php`,
  JSON_CATALOG: `${API_BASE_URL}/jsonList/jsonCatalog.php`,
  JSON_CATALOGEN: `${API_BASE_URL}/jsonList/jsonCatalogEn.php`,
};
